// =============================================
// roster.js - Official CoE Student Roster Validation
// =============================================

const Roster = (() => {
  const ENROLLED = [
    { name: "ADJALAINE GAGE MASOCOL", sex: "M", course: "BSCE", year: "1" },
    { name: "ALIPERIO JOHN II GOMEZ", sex: "M", course: "BSCE", year: "1" },
    { name: "ALMACIN JONAZH AIRO SALAYSAY", sex: "M", course: "BSCE", year: "1" },
    { name: "ALPUERTO LOUIE JAY VILLEGAS", sex: "M", course: "BSCE", year: "1" },
    { name: "ANIT KEIGO BINOYA", sex: "M", course: "BSCE", year: "1" },
    { name: "ARZADON DANIEL JAY ARELLANO", sex: "M", course: "BSCE", year: "1" },
    { name: "BALACY KENT JHON VILLAFLOR", sex: "M", course: "BSCE", year: "1" },
    { name: "BARRIENTOS DEVEN BOHOLST", sex: "M", course: "BSCE", year: "1" },
    { name: "BARRO ERN RASSEL JOHN", sex: "M", course: "BSCE", year: "1" },
    { name: "BASCO JARRUELLE SALIGUE", sex: "M", course: "BSCE", year: "1" },
    { name: "BONJOC JHYVY CARL MARISCAL", sex: "M", course: "BSCE", year: "1" },
    { name: "BUNAG JOEL JR. JAO", sex: "M", course: "BSCE", year: "1" },
    { name: "CABALUNA REVER JAMES LABADAN", sex: "M", course: "BSCE", year: "1" },
    { name: "CABONEGRO QUINCAR REMONDE", sex: "M", course: "BSCE", year: "1" },
    { name: "CABUDLAN ALEXANDER KENN PATANAO", sex: "M", course: "BSCE", year: "1" },
    { name: "CAÑETE LORENCE ESTREBA", sex: "M", course: "BSCE", year: "1" },
    { name: "CAPRICHO FRITZ PAGTIILAN", sex: "M", course: "BSCE", year: "1" },
    { name: "COMPE ROSELLER BRANGGAN", sex: "M", course: "BSCE", year: "1" },
    { name: "DACILLO JOHN ALIXIS FELIPE", sex: "M", course: "BSCE", year: "1" },
    { name: "DANTE JOHN REDDECK MAMAC", sex: "M", course: "BSCE", year: "1" },
    { name: "DAUGDAUG FRANCIS ALLAN PANTOJAN", sex: "M", course: "BSCE", year: "1" },
    { name: "DEL ROSARIO SAXONY SPENCER SALUBRE", sex: "M", course: "BSCE", year: "1" },
    { name: "DELA CALZADA GEOF AARON DIAZ", sex: "M", course: "BSCE", year: "1" },
    { name: "DELA CRUZ JOSEPH CHRISTOPHER MARISCAL", sex: "M", course: "BSCE", year: "1" },
    { name: "DELA CRUZ CHRIS DWAYNE SORIANO", sex: "M", course: "BSCE", year: "1" },
    { name: "DEMAULO REXSUR BASTATAS", sex: "M", course: "BSCE", year: "1" },
    { name: "ELIVERA LEMUEL JR BUNOG", sex: "M", course: "BSCE", year: "1" },
    { name: "ESCANER JMYR GLYNCH LABRADO", sex: "M", course: "BSCE", year: "1" },
    { name: "FABON BRIAN ELLICA", sex: "M", course: "BSCE", year: "1" },
    { name: "FERNANDEZ YEOJ VON JEO DAYAG", sex: "M", course: "BSCE", year: "1" },
    { name: "GARIGADE MARK HENRY SARAJENA", sex: "M", course: "BSCE", year: "1" },
    { name: "GERMAN ARVIE GUISADIO", sex: "M", course: "BSCE", year: "1" },
    { name: "GILAYO FRANZ DANIELJAY ALONZO", sex: "M", course: "BSCE", year: "1" },
    { name: "GOZE MICHAEL JAY ALBOROTO", sex: "M", course: "BSCE", year: "1" },
    { name: "INGAY BOBBY JAMES MALINDIG", sex: "M", course: "BSCE", year: "1" },
    { name: "ISIP PRINCE CARL TAMPOS", sex: "M", course: "BSCE", year: "1" },
    { name: "JOAQUIN KING ALDGIER SAN", sex: "M", course: "BSCE", year: "1" },
    { name: "LARANJO LEENRICK PAMAOS", sex: "M", course: "BSCE", year: "1" },
    { name: "LAUSA ANDRE SARCOL", sex: "M", course: "BSCE", year: "1" },
    { name: "LEGARTE KENNETH LAGUNA", sex: "M", course: "BSCE", year: "1" },
    { name: "LEMENTILLO KROIS MARTIN", sex: "M", course: "BSCE", year: "1" },
    { name: "LUCAYLUCAY MELVEY CORPUZ", sex: "M", course: "BSCE", year: "1" },
    { name: "MACAGBA JANZEN PETT MANGARON", sex: "M", course: "BSCE", year: "1" },
    { name: "MACROHON CHRISTIAN JAMES", sex: "M", course: "BSCE", year: "1" },
    { name: "MONTON ART JHONES CABINGATAN", sex: "M", course: "BSCE", year: "1" },
    { name: "NACITO RHENZ LEI ESTREMOS", sex: "M", course: "BSCE", year: "1" },
    { name: "NERI JOHN BRAINANT FERNANDEZ", sex: "M", course: "BSCE", year: "1" },
    { name: "OLOY CIE JAY SABAN", sex: "M", course: "BSCE", year: "1" },
    { name: "PANTA BRIAN DAVE BUAN", sex: "M", course: "BSCE", year: "1" },
    { name: "PARAYON SKY PACHECO", sex: "M", course: "BSCE", year: "1" },
    { name: "PELARION JHON FRITHS ARENILLA", sex: "M", course: "BSCE", year: "1" },
    { name: "PEREZ JOHN LLOYD SARASTE", sex: "M", course: "BSCE", year: "1" },
    { name: "PULVERA PAULO JUGUILON", sex: "M", course: "BSCE", year: "1" },
    { name: "PURACAN JAN BAGAY", sex: "M", course: "BSCE", year: "1" },
    { name: "QUITARA JAZFER JOHN BADUA", sex: "M", course: "BSCE", year: "1" },
    { name: "RAMA OWEN BLAKE", sex: "M", course: "BSCE", year: "1" },
    { name: "SABAYOG JERALD MANURAY", sex: "M", course: "BSCE", year: "1" },
    { name: "SALISE DIJAY GAPER", sex: "M", course: "BSCE", year: "1" },
    { name: "SAMEON KENT ALBERT", sex: "M", course: "BSCE", year: "1" },
    { name: "SANTOS RONN GABRIEL DELA CRUZ", sex: "M", course: "BSCE", year: "1" },
    { name: "TABUCAN JASON BENEDICT AGSAULIO", sex: "M", course: "BSCE", year: "1" },
    { name: "TECSON TRISTAN ANDOUEILI NOUV NUGAS", sex: "M", course: "BSCE", year: "1" },
    { name: "TIGAS CARL NELSON PELINGON", sex: "M", course: "BSCE", year: "1" },
    { name: "TIN-AO NEIL JOHN NIEVES", sex: "M", course: "BSCE", year: "1" },
    { name: "TUGADE KHIANNE JAKE ROCHA", sex: "M", course: "BSCE", year: "1" },
    { name: "UMBAY JHEMARL JOSEPH SAMORANOS", sex: "M", course: "BSCE", year: "1" },
    { name: "VAGILIDAD SETH ANGELO QUIBOYEN", sex: "M", course: "BSCE", year: "1" },
    { name: "VERGARA JAMES CHRISTOPHER MERCA", sex: "M", course: "BSCE", year: "1" },
    { name: "VILLANUEVA KYLE BLAISE SALAGOSTE", sex: "M", course: "BSCE", year: "1" },
    { name: "ALAGOS AALIYAH JANE ANAVA", sex: "F", course: "BSCE", year: "1" },
    { name: "ALBERCA MARIAN FERRARIN", sex: "F", course: "BSCE", year: "1" },
    { name: "BACAMANTE SHEENA CLAIRE MONEBA", sex: "F", course: "BSCE", year: "1" },
    { name: "BETONIO ANGEL KIRSTEN MYLES ROA", sex: "F", course: "BSCE", year: "1" },
    { name: "BONGGO CHERRY LOU DAVIN", sex: "F", course: "BSCE", year: "1" },
    { name: "CABONGCAL ANGEL REMISCAL", sex: "F", course: "BSCE", year: "1" },
    { name: "CASTRO RIANAH LEIGH MONTOJO", sex: "F", course: "BSCE", year: "1" },
    { name: "COLOBONG CHENISA MAE SEDON", sex: "F", course: "BSCE", year: "1" },
    { name: "DELA CRUZ CRYSTAL MAIDEN ABUNDA", sex: "F", course: "BSCE", year: "1" },
    { name: "DELA RAMA FRENCESS MAY DEQUIÑA", sex: "F", course: "BSCE", year: "1" },
    { name: "DIOSANA RM SOFIA BATOON", sex: "F", course: "BSCE", year: "1" },
    { name: "FABRIA LEXIS FAITH MAE CALMA", sex: "F", course: "BSCE", year: "1" },
    { name: "JECKSON BELLE MASAGLANG", sex: "F", course: "BSCE", year: "1" },
    { name: "LAGANSUA REISHA JOVINICA TAPADO", sex: "F", course: "BSCE", year: "1" },
    { name: "MARTINEZ CHANNELE MAE", sex: "F", course: "BSCE", year: "1" },
    { name: "MASAYAO VALERIE CUTAY", sex: "F", course: "BSCE", year: "1" },
    { name: "MEJIAS CHEDIN SHANE SOLUTAN", sex: "F", course: "BSCE", year: "1" },
    { name: "MELLANES ANGEL MAE GELARDERO", sex: "F", course: "BSCE", year: "1" },
    { name: "MOLIETA PRENCESS JOY MIGUEL", sex: "F", course: "BSCE", year: "1" },
    { name: "MOMO ALEZA MONTEZA", sex: "F", course: "BSCE", year: "1" },
    { name: "OTON PRINCESS ANGEL CARLOS", sex: "F", course: "BSCE", year: "1" },
    { name: "PACLEB LETTICE PHOEBE PALMARES", sex: "F", course: "BSCE", year: "1" },
    { name: "PACQUIAO NOVIELINE PASCUA", sex: "F", course: "BSCE", year: "1" },
    { name: "PRE LYZA JOY OBEREZ", sex: "F", course: "BSCE", year: "1" },
    { name: "RELATADO PRINCESS ANNE SILVERO", sex: "F", course: "BSCE", year: "1" },
    { name: "REPOSAR NYCE ANGELA NARIT", sex: "F", course: "BSCE", year: "1" },
    { name: "SARDIDO MAERU LEORNAS", sex: "F", course: "BSCE", year: "1" },
    { name: "TABALWAN ANTONETTE AGUSTIN", sex: "F", course: "BSCE", year: "1" },
    { name: "TANTE LIANNE JANE ROMERO", sex: "F", course: "BSCE", year: "1" },
    { name: "VILLANUEVA BLESSIE YZAVEL CABRERA", sex: "F", course: "BSCE", year: "1" },
    { name: "ALBANO CLARK LAWRENCE CASAGDA", sex: "M", course: "BSCE", year: "2" },
    { name: "ALBARRACIN ALESTAIR RAFAEL FERNANDEZ", sex: "M", course: "BSCE", year: "2" },
    { name: "ALCONERA AIDEEN NASH PACILAN", sex: "M", course: "BSCE", year: "2" },
    { name: "ALPANTA SHAWN ALLEN GONZALES", sex: "M", course: "BSCE", year: "2" },
    { name: "ASUGAS SHERMIE JAY ABRENILLA", sex: "M", course: "BSCE", year: "2" },
    { name: "CASTROMAYOR VICENTE III PATOS", sex: "M", course: "BSCE", year: "2" },
    { name: "COBOL ANTONN VINCE LAPEÑA", sex: "M", course: "BSCE", year: "2" },
    { name: "CUDAL ALAN LLYOD CANDIA", sex: "M", course: "BSCE", year: "2" },
    { name: "DANO JANUS FRANCEDALE RONNIEL ELNAR", sex: "M", course: "BSCE", year: "2" },
    { name: "DAYANGCO RYAN ROY ORDANEZA", sex: "M", course: "BSCE", year: "2" },
    { name: "DEPALUBOS EUGENE CASTILLO", sex: "M", course: "BSCE", year: "2" },
    { name: "DINGLASA RUDJARD BENEDICT MENDOZA", sex: "M", course: "BSCE", year: "2" },
    { name: "DIZON JANEAU MYRR YAMOMO", sex: "M", course: "BSCE", year: "2" },
    { name: "DUMAYAS AXELL ROMANO", sex: "M", course: "BSCE", year: "2" },
    { name: "ENDRINA JON ALLEN TROY", sex: "M", course: "BSCE", year: "2" },
    { name: "ESTRADA JOSHUA KADMIEL", sex: "M", course: "BSCE", year: "2" },
    { name: "ETIK RONY ALASIDA", sex: "M", course: "BSCE", year: "2" },
    { name: "GEALON GIAN LORENCE DELFIN", sex: "M", course: "BSCE", year: "2" },
    { name: "GIMAL REED PENOLIAD", sex: "M", course: "BSCE", year: "2" },
    { name: "GOC-ONG JUSTINE DWYANE NONOL", sex: "M", course: "BSCE", year: "2" },
    { name: "HILACAN WINMIER RYAN SANI", sex: "M", course: "BSCE", year: "2" },
    { name: "LAVISURES JUPHYLL DWAYNE CARAG", sex: "M", course: "BSCE", year: "2" },
    { name: "MACASIPOT ANUAR MARAON", sex: "M", course: "BSCE", year: "2" },
    { name: "MADEL RUFAMER SARONA", sex: "M", course: "BSCE", year: "2" },
    { name: "MAMBALING FRANCE PATRICK BELLO", sex: "M", course: "BSCE", year: "2" },
    { name: "MIDSAPAK MARK JASPER RAZONABLE", sex: "M", course: "BSCE", year: "2" },
    { name: "MIRALLES CHARLES ALBERT DAVE ADLAWAN", sex: "M", course: "BSCE", year: "2" },
    { name: "MONIÑO JHESS ANDREI VILLORIJO", sex: "M", course: "BSCE", year: "2" },
    { name: "MORTES KENT RUZZEL PAGUNSAN", sex: "M", course: "BSCE", year: "2" },
    { name: "NAVARRO LEBRON JAMES MORANTE", sex: "M", course: "BSCE", year: "2" },
    { name: "NILLAS JASPER GALLA", sex: "M", course: "BSCE", year: "2" },
    { name: "OÑEZ JOHN LLOYD CUEVAS", sex: "M", course: "BSCE", year: "2" },
    { name: "PATRICIO ACHELIS CELLEROS", sex: "M", course: "BSCE", year: "2" },
    { name: "PEREZ REYNAN JOSH ZAMORA", sex: "M", course: "BSCE", year: "2" },
    { name: "QUION MARL LYNDON MAIT", sex: "M", course: "BSCE", year: "2" },
    { name: "RELATADO ERIC CRYZ DUMAYAS", sex: "M", course: "BSCE", year: "2" },
    { name: "RELLON DUSTHINE LOUIE SABIDOR", sex: "M", course: "BSCE", year: "2" },
    { name: "SALES LEAN JAMES BAGUIOSO", sex: "M", course: "BSCE", year: "2" },
    { name: "SANIEL ERN RYANN BARRO", sex: "M", course: "BSCE", year: "2" },
    { name: "SANOY AUSTON KEITH", sex: "M", course: "BSCE", year: "2" },
    { name: "SARA RYAN DAVE DAUB", sex: "M", course: "BSCE", year: "2" },
    { name: "SEDON JANOEL CHRIS DIGAN", sex: "M", course: "BSCE", year: "2" },
    { name: "SOLLANO JOHN LLOYD SANTILLAN", sex: "M", course: "BSCE", year: "2" },
    { name: "SUMILHIG JOHN JAY BERNALES", sex: "M", course: "BSCE", year: "2" },
    { name: "TAJON BRANDON LACROIX RODRIGUEZ", sex: "M", course: "BSCE", year: "2" },
    { name: "TAKBILANI II GERARLD JATULA", sex: "M", course: "BSCE", year: "2" },
    { name: "TANADOR JAMES ROY ALIMANIO", sex: "M", course: "BSCE", year: "2" },
    { name: "TECSON MARJUBO CAYA", sex: "M", course: "BSCE", year: "2" },
    { name: "TORTAL BRANDO JHEE MATAB", sex: "M", course: "BSCE", year: "2" },
    { name: "UBUNGEN GABRIEL BALLOS", sex: "M", course: "BSCE", year: "2" },
    { name: "ABALLE CHERISH ANN ELTAGONDE", sex: "F", course: "BSCE", year: "2" },
    { name: "ABRENILLA JEAN ROSE RAMOS", sex: "F", course: "BSCE", year: "2" },
    { name: "AGRAVIADOR DAISY JANE SORIA", sex: "F", course: "BSCE", year: "2" },
    { name: "BURGOS SAHNESSA MAEDELLE FERNANDEZ", sex: "F", course: "BSCE", year: "2" },
    { name: "CABALLERO NETZYL KATE SECRETARIA", sex: "F", course: "BSCE", year: "2" },
    { name: "CABANDA KEZZIAH GRACE ENON", sex: "F", course: "BSCE", year: "2" },
    { name: "CABLAYDA QIN MHARWHYLL ENCALLADO", sex: "F", course: "BSCE", year: "2" },
    { name: "CADAYONA KAREL CHRISTY LEIGH ELTAGONDE", sex: "F", course: "BSCE", year: "2" },
    { name: "DATOC GINNEJO EMBOC", sex: "F", course: "BSCE", year: "2" },
    { name: "DE CASTRO JERAME SUMANDIG", sex: "F", course: "BSCE", year: "2" },
    { name: "DELA CRUZ PAMELA PALULIM", sex: "F", course: "BSCE", year: "2" },
    { name: "DONATO ERICA MARIE DIEZ", sex: "F", course: "BSCE", year: "2" },
    { name: "DUÑO JEVA OPONG", sex: "F", course: "BSCE", year: "2" },
    { name: "GADOR GABRIELLE NONETTE MERCA", sex: "F", course: "BSCE", year: "2" },
    { name: "GALENDEZ KAYLA CAPUYAN", sex: "F", course: "BSCE", year: "2" },
    { name: "GALEOS CATHY SUMALBANG", sex: "F", course: "BSCE", year: "2" },
    { name: "IBIS ALIYAH VANESSA BAYARCAL", sex: "F", course: "BSCE", year: "2" },
    { name: "JANOLGUE CHEZZA MAE RABAGO", sex: "F", course: "BSCE", year: "2" },
    { name: "LAYGAN MARIBETH MANTILLA", sex: "F", course: "BSCE", year: "2" },
    { name: "LEE KEIRA ALBORES", sex: "F", course: "BSCE", year: "2" },
    { name: "LILIO MARYVELLE XANE DECOLAS", sex: "F", course: "BSCE", year: "2" },
    { name: "MALIMBAG ALLEN GRACE BALILI", sex: "F", course: "BSCE", year: "2" },
    { name: "MANTALABA FHEIL THEA MAINIT", sex: "F", course: "BSCE", year: "2" },
    { name: "OCHEA SHEJARAH KARIZ CAMABANG", sex: "F", course: "BSCE", year: "2" },
    { name: "OPLE ELLA MAE BELANO", sex: "F", course: "BSCE", year: "2" },
    { name: "OSORIO LIANE ERIS YAP", sex: "F", course: "BSCE", year: "2" },
    { name: "PACURA AIZA PARUNGAO", sex: "F", course: "BSCE", year: "2" },
    { name: "PANUGALON CLEAH SALISE", sex: "F", course: "BSCE", year: "2" },
    { name: "RABOR LYKA JANE HAGUIMIT", sex: "F", course: "BSCE", year: "2" },
    { name: "ROCACORBA AZZYRA TARNATE", sex: "F", course: "BSCE", year: "2" },
    { name: "SALIHUDIN NORRANE SALASAIN", sex: "F", course: "BSCE", year: "2" },
    { name: "SILANOVA AYESSA GRACE MABAO", sex: "F", course: "BSCE", year: "2" },
    { name: "SOMBILON RIZZA ELAINE SANTIAGO", sex: "F", course: "BSCE", year: "2" },
    { name: "SORIZO MEDY JESSEL TULIN", sex: "F", course: "BSCE", year: "2" },
    { name: "VILLALUZ ASHLEY DELA PEÑA", sex: "F", course: "BSCE", year: "2" },
    { name: "BACALLA MARK JOHNRIEL COLE", sex: "M", course: "BSCE", year: "3" },
    { name: "BARON RODINIEL ALFARERO", sex: "M", course: "BSCE", year: "3" },
    { name: "COBOL GIL DREXEL SAMEON", sex: "M", course: "BSCE", year: "3" },
    { name: "CURIMAO STEVEN JOSH AMADAR", sex: "M", course: "BSCE", year: "3" },
    { name: "DE TORRES KARL DAVID CATEDRAL", sex: "M", course: "BSCE", year: "3" },
    { name: "DIDA-AGUN NAIF ALI", sex: "M", course: "BSCE", year: "3" },
    { name: "DONAL LESTER TAMPIPI", sex: "M", course: "BSCE", year: "3" },
    { name: "DOONG KURT VINCENT PASCUAL", sex: "M", course: "BSCE", year: "3" },
    { name: "DUGADUGA MARCO MIGUEL LIAZ", sex: "M", course: "BSCE", year: "3" },
    { name: "EMPLEO PRINCE CEDRIC SANTOS", sex: "M", course: "BSCE", year: "3" },
    { name: "FERNANDEZ JEVEN PANGILINAN", sex: "M", course: "BSCE", year: "3" },
    { name: "GALEOS JOSHUA ROQUERO", sex: "M", course: "BSCE", year: "3" },
    { name: "INOT KIVEN A-O", sex: "M", course: "BSCE", year: "3" },
    { name: "MANALUNDONG SOFIAN DIMACUTA", sex: "M", course: "BSCE", year: "3" },
    { name: "MEDEZ HOWEN GLIMADA", sex: "M", course: "BSCE", year: "3" },
    { name: "MENCHAVEZ IVAN RAGANAS", sex: "M", course: "BSCE", year: "3" },
    { name: "MONTE JUSTINE CLARK CAMILLO", sex: "M", course: "BSCE", year: "3" },
    { name: "NAVAJA DAVE BARON", sex: "M", course: "BSCE", year: "3" },
    { name: "NEROSA SEAN KYLE BAURA", sex: "M", course: "BSCE", year: "3" },
    { name: "OLANDA JASPER RAVEN OMBLERO", sex: "M", course: "BSCE", year: "3" },
    { name: "PARANTAR ALVIC JUDE CRALISOS", sex: "M", course: "BSCE", year: "3" },
    { name: "PASCUAL ZYRUS BRITZ LIGTAS", sex: "M", course: "BSCE", year: "3" },
    { name: "PATOS RENZ RYLLE APITAN", sex: "M", course: "BSCE", year: "3" },
    { name: "REVILLEZA FREDDIRICK ALBETE", sex: "M", course: "BSCE", year: "3" },
    { name: "RICAPLAZA CHRISTIAN DOMINIC DAMPIGANON", sex: "M", course: "BSCE", year: "3" },
    { name: "RUBI KENT RANCIL JAY CAPUL", sex: "M", course: "BSCE", year: "3" },
    { name: "SANDOVAL CLARENCE JAKE CABATAS", sex: "M", course: "BSCE", year: "3" },
    { name: "SIA JOHN PAUL RELUCIO", sex: "M", course: "BSCE", year: "3" },
    { name: "SOLITANA CLINT ANTHONY JACA", sex: "M", course: "BSCE", year: "3" },
    { name: "SOMERA JHAN LLOYD ALBERCA", sex: "M", course: "BSCE", year: "3" },
    { name: "TAMPOS STEPHEN ZIEDIELOU ABAWAG", sex: "M", course: "BSCE", year: "3" },
    { name: "TERANDO FRANCIS SALAZAR", sex: "M", course: "BSCE", year: "3" },
    { name: "ULGARAN CHRISTIAN DAVE HOCAMIS", sex: "M", course: "BSCE", year: "3" },
    { name: "VIRAN BRIAN JOSHUA", sex: "M", course: "BSCE", year: "3" },
    { name: "VIRTUDAZO KWAYNE KERK ALPACION", sex: "M", course: "BSCE", year: "3" },
    { name: "ABANILLA MECHELLE MAMANAO", sex: "F", course: "BSCE", year: "3" },
    { name: "AMARILLO JOHANNAH LAYE ESPINO", sex: "F", course: "BSCE", year: "3" },
    { name: "AROMA THERRENCE LUYONG", sex: "F", course: "BSCE", year: "3" },
    { name: "BITANGA HERSHEY YUIE GEE CARPENTERO", sex: "F", course: "BSCE", year: "3" },
    { name: "BOLANIO IZA BUSMEON", sex: "F", course: "BSCE", year: "3" },
    { name: "BRACERO BRYCEL CYAN TEODOSIO", sex: "F", course: "BSCE", year: "3" },
    { name: "CABARAL ALLIAH JANE LAURONAL", sex: "F", course: "BSCE", year: "3" },
    { name: "CADAYONA BRITNEY JOYCE DEGAMO", sex: "F", course: "BSCE", year: "3" },
    { name: "CALAMBA QUENNIE XENIA LLAPITAN", sex: "F", course: "BSCE", year: "3" },
    { name: "CALESA RONNAH GELE POLINIO", sex: "F", course: "BSCE", year: "3" },
    { name: "CASTOR MA. KRISTINA CASANDRA MORALLA", sex: "F", course: "BSCE", year: "3" },
    { name: "DEPALUBOS LEZELME BASINO", sex: "F", course: "BSCE", year: "3" },
    { name: "ELTAGONDE BEAH BIANCA FERMO", sex: "F", course: "BSCE", year: "3" },
    { name: "ENAD ANICA KAYE JERUSALEM", sex: "F", course: "BSCE", year: "3" },
    { name: "FUENTES ALYSSA", sex: "F", course: "BSCE", year: "3" },
    { name: "GAVIOLA CHARIZZE MAXEEN ANDRES", sex: "F", course: "BSCE", year: "3" },
    { name: "JUSTINIANE ANDREA VANNA PILVERA", sex: "F", course: "BSCE", year: "3" },
    { name: "MEJIAS QUEEN FLORES", sex: "F", course: "BSCE", year: "3" },
    { name: "MODELO RICA MAE PUSODAN", sex: "F", course: "BSCE", year: "3" },
    { name: "MONTEZA RONNA LAMBO", sex: "F", course: "BSCE", year: "3" },
    { name: "MUSA NHADZMA MUSA", sex: "F", course: "BSCE", year: "3" },
    { name: "OGOY RHEA MEA LABATA", sex: "F", course: "BSCE", year: "3" },
    { name: "ORIC VANESSA RASOLA", sex: "F", course: "BSCE", year: "3" },
    { name: "POLICARPIO VICTORIA KXNDRA LABURADA", sex: "F", course: "BSCE", year: "3" },
    { name: "RELATIVO MAY FRANCES DALISAN", sex: "F", course: "BSCE", year: "3" },
    { name: "RIVERA KATE ANGELA AGNES", sex: "F", course: "BSCE", year: "3" },
    { name: "SALADO MEKAILA BALDERAS", sex: "F", course: "BSCE", year: "3" },
    { name: "SANCHEZ GRACIE MAE CARDENAS", sex: "F", course: "BSCE", year: "3" },
    { name: "SANTANDER RISSAH MAE LOZANO", sex: "F", course: "BSCE", year: "3" },
    { name: "SATAR NORHAISAH BALINDONG", sex: "F", course: "BSCE", year: "3" },
    { name: "SPACIO EUGIE LYN ALABATA", sex: "F", course: "BSCE", year: "3" },
    { name: "TAPOROC CHASMAE ANGEL ESTOMATA", sex: "F", course: "BSCE", year: "3" },
    { name: "VALDEZ DEBORAH ESMERALDA", sex: "F", course: "BSCE", year: "3" },
    { name: "ALFEREZ CHRISTIAN KYLE MANCERA", sex: "M", course: "BSCE", year: "4" },
    { name: "AMBAT RENE JR. MALAKI", sex: "M", course: "BSCE", year: "4" },
    { name: "AMOGUIS NEICO CEPEDA", sex: "M", course: "BSCE", year: "4" },
    { name: "AYOP WILSON JR. PONGARON", sex: "M", course: "BSCE", year: "4" },
    { name: "BARCENA CARL JHON MICHAEL ULLA", sex: "M", course: "BSCE", year: "4" },
    { name: "BENDIJO RAVEN JAMES GRAVINO", sex: "M", course: "BSCE", year: "4" },
    { name: "BURA-AY WEL JOHN BAYO", sex: "M", course: "BSCE", year: "4" },
    { name: "CABALAR JAKE CYBEN ABELLA", sex: "M", course: "BSCE", year: "4" },
    { name: "CANITAN REGEL ALBERCA", sex: "M", course: "BSCE", year: "4" },
    { name: "CARVAJAL ROLANDO I I I SANTE", sex: "M", course: "BSCE", year: "4" },
    { name: "CELOCIA AIRON JAY MERCADEROS", sex: "M", course: "BSCE", year: "4" },
    { name: "CERVANTES JEANELYN ALBO", sex: "M", course: "BSCE", year: "4" },
    { name: "CRISMUNDO JAY LOYD BEMOS", sex: "M", course: "BSCE", year: "4" },
    { name: "DELA CRUZ ANTOINE CHRISTOPHER PALULIM", sex: "M", course: "BSCE", year: "4" },
    { name: "DELA CRUZ JARON JOHN AQUINO", sex: "M", course: "BSCE", year: "4" },
    { name: "DELA CRUZ MARK GLOURENCE CASTIGADOR", sex: "M", course: "BSCE", year: "4" },
    { name: "DELA TORRE JAN LLOYD TANDUYAN", sex: "M", course: "BSCE", year: "4" },
    { name: "EMBAC ANGELO JANRY ADAYA", sex: "M", course: "BSCE", year: "4" },
    { name: "ESPINOSA HERMINIO III VILO", sex: "M", course: "BSCE", year: "4" },
    { name: "ESTANIO JHAKE BERNALES", sex: "M", course: "BSCE", year: "4" },
    { name: "GALARAGA JAYBERT MATA", sex: "M", course: "BSCE", year: "4" },
    { name: "LASQUITE KEITH ZEUS ADORABLE", sex: "M", course: "BSCE", year: "4" },
    { name: "LUZON JAMES CHRISTIAN SAGOLILI", sex: "M", course: "BSCE", year: "4" },
    { name: "MAGALLANES SEANNE LOUIS RUTHERLOU MAÑALAC", sex: "M", course: "BSCE", year: "4" },
    { name: "OLIVERIO PRINCE MOZART ESTEBAN", sex: "M", course: "BSCE", year: "4" },
    { name: "OPPUS KLINT LAWRENCE DAGOHOY", sex: "M", course: "BSCE", year: "4" },
    { name: "PANGAN JOHN ANILOVF LUCEÑO", sex: "M", course: "BSCE", year: "4" },
    { name: "PASCUA JOHN LORENZ DELA CRUZ", sex: "M", course: "BSCE", year: "4" },
    { name: "PATONG JOSEPH VINCENT CADOTDOT", sex: "M", course: "BSCE", year: "4" },
    { name: "SALAZAR GABRIEL SEBASTIAN DUMARAN", sex: "M", course: "BSCE", year: "4" },
    { name: "SANDICO JOHN ASHLEY", sex: "M", course: "BSCE", year: "4" },
    { name: "SUSANO RANDY JR. NACUA", sex: "M", course: "BSCE", year: "4" },
    { name: "TANGA-AN ALEX JR. GORNES", sex: "M", course: "BSCE", year: "4" },
    { name: "TINAMBACAN CHARLES MELVILLE CELERES", sex: "M", course: "BSCE", year: "4" },
    { name: "ALMOJADE FREXYL MAE MIRANTE", sex: "F", course: "BSCE", year: "4" },
    { name: "ANAR KYLA PRATO", sex: "F", course: "BSCE", year: "4" },
    { name: "ANTIOLA DEBIE RONDINA", sex: "F", course: "BSCE", year: "4" },
    { name: "ARBAAN SHANDY ALEXA GAMUTIN", sex: "F", course: "BSCE", year: "4" },
    { name: "BACALLA REJEAN ALFEREZ", sex: "F", course: "BSCE", year: "4" },
    { name: "BACALSO MICHELLE UNGGAN", sex: "F", course: "BSCE", year: "4" },
    { name: "BAUTISTA JEANETTE MAE POJAS", sex: "F", course: "BSCE", year: "4" },
    { name: "CABALDA JULIANA JANE JASME", sex: "F", course: "BSCE", year: "4" },
    { name: "CANONIGO HEREANNE DIOSANA", sex: "F", course: "BSCE", year: "4" },
    { name: "CAPOYAN LHALEEN SAROMINES", sex: "F", course: "BSCE", year: "4" },
    { name: "DARUG CHRISTINE ISABEL LAPINIG", sex: "F", course: "BSCE", year: "4" },
    { name: "DEGORIO SANDARA LOUISE PALMES", sex: "F", course: "BSCE", year: "4" },
    { name: "DICAP KARRYL MAE SANDICO", sex: "F", course: "BSCE", year: "4" },
    { name: "DIEZ JASHMINE VILLAR", sex: "F", course: "BSCE", year: "4" },
    { name: "GALULO KRIZZA JOY TALINGTING", sex: "F", course: "BSCE", year: "4" },
    { name: "GEVEROLA CHRIZYLLE KEITH", sex: "F", course: "BSCE", year: "4" },
    { name: "GUINOLONG HAFSA MAUTANTE", sex: "F", course: "BSCE", year: "4" },
    { name: "JAGNA KATE ENCARNACION", sex: "F", course: "BSCE", year: "4" },
    { name: "LANTAPE TRIXIE CAHILES", sex: "F", course: "BSCE", year: "4" },
    { name: "LIM MARJORIE ANTA", sex: "F", course: "BSCE", year: "4" },
    { name: "MARAGAÑAS KCEZIAH BAJENTING", sex: "F", course: "BSCE", year: "4" },
    { name: "NAVARRO KATE ROXANNE CANSANCIO", sex: "F", course: "BSCE", year: "4" },
    { name: "RABANES SAMANTA ESTRELLOSO", sex: "F", course: "BSCE", year: "4" },
    { name: "RUELAN KAYE ALESSANDRA MAHINAY", sex: "F", course: "BSCE", year: "4" },
    { name: "SAGARAY RENNA JANE GUANZON", sex: "F", course: "BSCE", year: "4" },
    { name: "SAVILLO SEPH GEMA OBAS", sex: "F", course: "BSCE", year: "4" },
    { name: "SONGKIT KATRINA PAMELA DAMOLE", sex: "F", course: "BSCE", year: "4" },
    { name: "TORRECAMPO GINPE NOVINO", sex: "F", course: "BSCE", year: "4" },
    { name: "BAGAAN CYRUS DAVE", sex: "M", course: "BSCE", year: "5" },
    { name: "BUHISAN JOHNRICH ANTONI DUMOGHO", sex: "M", course: "BSCE", year: "5" },
    { name: "FLORES JEFFERSON MARTIN", sex: "M", course: "BSCE", year: "5" },
    { name: "LINES JAKE SAMSON", sex: "M", course: "BSCE", year: "5" },
    { name: "RABANZO RENMARC CONTINIDAS", sex: "M", course: "BSCE", year: "5" },
    { name: "SARABILLO CHARLES DEVILLERES", sex: "M", course: "BSCE", year: "5" },
    { name: "SIPAT JOHN ROBERT PABALATE", sex: "M", course: "BSCE", year: "5" },
    { name: "SUPERALES MICHAEL ZEDRIC ESPAÑOL", sex: "M", course: "BSCE", year: "5" },
    { name: "ZULITA VINCE JIKYSER BARON", sex: "M", course: "BSCE", year: "5" },
    { name: "MANZO JANSSEN MAG-ASO", sex: "F", course: "BSCE", year: "5" },
    { name: "PARAISO VHEA MONIQUE DELA VIÑA", sex: "F", course: "BSCE", year: "5" },
    { name: "REMONDE NIKIE GERAL", sex: "F", course: "BSCE", year: "5" },
    { name: "ABARCA CARL ARDRIAN GUIBONE", sex: "M", course: "BSCoE", year: "1" },
    { name: "ALMEDA MARC NAVARRO", sex: "M", course: "BSCoE", year: "1" },
    { name: "CENTENO JERRAIDEE CABREROS", sex: "M", course: "BSCoE", year: "1" },
    { name: "CORESIS JOHN EARL CONTRERAS", sex: "M", course: "BSCoE", year: "1" },
    { name: "GAMUTIN ETHAN BRADLEI TERANTE", sex: "M", course: "BSCoE", year: "1" },
    { name: "GOC-ONG VLADIMIR JULES YONGCO", sex: "M", course: "BSCoE", year: "1" },
    { name: "KINGCO ZJ JULES MONROID", sex: "M", course: "BSCoE", year: "1" },
    { name: "QUINONES KIRT GIAN CENTINO", sex: "M", course: "BSCoE", year: "1" },
    { name: "IPAL MARIEL GAMBOA", sex: "F", course: "BSCoE", year: "1" },
    { name: "REYES CRISTINA MARIE BACOMO", sex: "F", course: "BSCoE", year: "1" },
    { name: "ROBILLOS CHRISTINE ANGEL BACALSO", sex: "F", course: "BSCoE", year: "1" },
    { name: "AROBO RALPH ANGELO ADOLFO", sex: "M", course: "BSCoE", year: "2" },
    { name: "ATIL ISAAC ISAIAH DELA PEÑA", sex: "M", course: "BSCoE", year: "2" },
    { name: "BIMBO LANCE XYZHERLEE ALFECHE", sex: "M", course: "BSCoE", year: "2" },
    { name: "DELFIN XANDER GUILBERT NOLASCO", sex: "M", course: "BSCoE", year: "2" },
    { name: "MORADA REINENS BRYN OBACH", sex: "M", course: "BSCoE", year: "2" },
    { name: "RIVERA MERVIN JOHN BARITOGO", sex: "M", course: "BSCoE", year: "2" },
    { name: "TAGOSE JASPER JOASH JULIE", sex: "M", course: "BSCoE", year: "2" },
    { name: "TAMPOS REDNEY GUARDAQUIVIL", sex: "F", course: "BSCoE", year: "2" },
    { name: "BONCAVIL JOSEPH KARL VENCER", sex: "M", course: "BSCoE", year: "3" },
    { name: "CARILLO DARYL DAVE UTBO", sex: "M", course: "BSCoE", year: "3" },
    { name: "MELENDRES ULYSSES HERMOSO", sex: "M", course: "BSCoE", year: "3" },
    { name: "VILLACORTA JAMES ANTHONY DICDICAN", sex: "M", course: "BSCoE", year: "3" },
    { name: "SACIL ANTHONY CLARK BON MALABJA", sex: "M", course: "BSCoE", year: "4" },
    { name: "HERMITA LEAH ANGELA BAYNOSA", sex: "F", course: "BSCoE", year: "6" },
    { name: "ANIÑON BRYAN DAVE CABANADA", sex: "M", course: "BSECE", year: "1" },
    { name: "BUHISAN JEMUEL JANABAN", sex: "M", course: "BSECE", year: "1" },
    { name: "CARDIÑO MARK RONALD CALATCAT", sex: "M", course: "BSECE", year: "1" },
    { name: "CEDEÑO ALEXIS JR. GEONZON", sex: "M", course: "BSECE", year: "1" },
    { name: "DAHIROC AVY JAY ENAD", sex: "M", course: "BSECE", year: "1" },
    { name: "DASMARIÑAS FRANCCO GELVERO", sex: "M", course: "BSECE", year: "1" },
    { name: "ESCALANTE KIERKIVEN SANCHEZ", sex: "M", course: "BSECE", year: "1" },
    { name: "GOMEZ DENZEL FLORENTINO", sex: "M", course: "BSECE", year: "1" },
    { name: "GUBANTES EZRA LOYD PAMAOS", sex: "M", course: "BSECE", year: "1" },
    { name: "GUERRA ART TERRENCE CODEÑO", sex: "M", course: "BSECE", year: "1" },
    { name: "ILISAN ZIDRECK SATUMCACAL", sex: "M", course: "BSECE", year: "1" },
    { name: "LANGAMON CYRUS JAMES TABERNA", sex: "M", course: "BSECE", year: "1" },
    { name: "LAQUINON NUVS BAJAO", sex: "M", course: "BSECE", year: "1" },
    { name: "MABIDA PAUL JOSHUA SABINO", sex: "M", course: "BSECE", year: "1" },
    { name: "MEJILLANO PRINCE DARY", sex: "M", course: "BSECE", year: "1" },
    { name: "OMEGA ALVIN ELLACER", sex: "M", course: "BSECE", year: "1" },
    { name: "PAN BRYAN JAMES ATAWAN", sex: "M", course: "BSECE", year: "1" },
    { name: "PANAL JESU MIKE DEPALUBOS", sex: "M", course: "BSECE", year: "1" },
    { name: "REGIDOR MACARIO FRANCISCO", sex: "M", course: "BSECE", year: "1" },
    { name: "RUCA REY MARK SARDIDO", sex: "M", course: "BSECE", year: "1" },
    { name: "SURPOSA KURT NATIVIDAD", sex: "M", course: "BSECE", year: "1" },
    { name: "ADOLFO ZHEA ELAINE REMOROZA", sex: "F", course: "BSECE", year: "1" },
    { name: "ARELLANO JUBELYN PARRENO", sex: "F", course: "BSECE", year: "1" },
    { name: "ELORCHA ARIAN JANE CANOY", sex: "F", course: "BSECE", year: "1" },
    { name: "GUMERA KHEAN ARANETA", sex: "F", course: "BSECE", year: "1" },
    { name: "NAVAREZ CAMILLE ROSE PARADERO", sex: "F", course: "BSECE", year: "1" },
    { name: "RELLOSO LORIDEL AÑASCO", sex: "F", course: "BSECE", year: "1" },
    { name: "ROÑO CAITLEEN SILMARIEN REYES", sex: "F", course: "BSECE", year: "1" },
    { name: "AGUANTA CHRISTIAN JOHN DELUVIO", sex: "M", course: "BSECE", year: "2" },
    { name: "BORLADO SEBASTIEN ANDREI SABAYLE", sex: "M", course: "BSECE", year: "2" },
    { name: "CASTRONUEVO CHRISTIAN JOYZE TINAMBACAN", sex: "M", course: "BSECE", year: "2" },
    { name: "DAÑGO LANHIEL KENN ARICAYOS", sex: "M", course: "BSECE", year: "2" },
    { name: "LUMBA ARCHIE NUGAS", sex: "M", course: "BSECE", year: "2" },
    { name: "MAMAC CORNELIO JOSE SANDOVAL", sex: "M", course: "BSECE", year: "2" },
    { name: "MANALANG SANTIAGO RAFAEL DODOSO", sex: "M", course: "BSECE", year: "2" },
    { name: "NACUA KINSLEY QUIMADA", sex: "M", course: "BSECE", year: "2" },
    { name: "NEROSA FERNAN CARL ORTEGA", sex: "M", course: "BSECE", year: "2" },
    { name: "PACAÑA KYLE GREGOR GUMANAY", sex: "M", course: "BSECE", year: "2" },
    { name: "PELLETERO KARL NICOLI SEGISMUNDO", sex: "M", course: "BSECE", year: "2" },
    { name: "TALINGTING KENNETH LANCE", sex: "M", course: "BSECE", year: "2" },
    { name: "BOOC KEITHLEEN FAITH BINGIL", sex: "F", course: "BSECE", year: "2" },
    { name: "GERALDINO TRISA MAE TABIGUE", sex: "F", course: "BSECE", year: "2" },
    { name: "ADARO VIENZ EDHRIAN OLING", sex: "M", course: "BSECE", year: "3" },
    { name: "CAPONES ROSS ALFRED RECREO", sex: "M", course: "BSECE", year: "3" },
    { name: "CASTILLO FRANCIS BURLAZA", sex: "M", course: "BSECE", year: "3" },
    { name: "MALILONG JUMAYCA ROSE BABALCON", sex: "F", course: "BSECE", year: "3" },
    { name: "MANAIT LORIE MAE BRIGOLE", sex: "F", course: "BSECE", year: "3" },
    { name: "MANDO MICHAELA JANE RESUTAY", sex: "F", course: "BSECE", year: "3" },
    { name: "BOCADO JOHN MICHAEL ITING", sex: "M", course: "BSECE", year: "4" },
    { name: "FEDREQUILAN GLENN GALIZA", sex: "M", course: "BSECE", year: "4" },
    { name: "LIPATA MARK KHENNETH", sex: "M", course: "BSECE", year: "4" },
    { name: "PADEN KEN MORALES", sex: "M", course: "BSECE", year: "4" },
    { name: "GLORIA KURT LAURENCE DIAMANTE", sex: "M", course: "BSECE", year: "5" },
    { name: "SILVA ELMER CHRISTIAN BALILI", sex: "M", course: "BSECE", year: "5" }
  ];

  // Tokenize & normalize a name string (lowercase, remove punctuation, split into words)
  function tokenize(str) {
    if (!str) return [];
    return str
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "") // strip accents/diacritics
      .replace(/[^a-z0-9\s]/g, " ")
      .split(/\s+/)
      .filter(t => t.length > 0 && t !== "jr" && t !== "sr" && t !== "iii" && t !== "ii" && t !== "na");
  }

  // Find a student record by matching name tokens
  function findStudent(fullName) {
    if (!fullName || typeof fullName !== "string") return null;
    const searchTokens = tokenize(fullName);
    if (searchTokens.length === 0) return null;

    let bestMatch = null;
    let maxMatchCount = 0;

    for (const student of ENROLLED) {
      const studentTokens = tokenize(student.name);
      let matchCount = 0;
      for (const st of searchTokens) {
        if (studentTokens.includes(st)) {
          matchCount++;
        }
      }

      if (matchCount >= 2 && matchCount > maxMatchCount) {
        maxMatchCount = matchCount;
        bestMatch = student;
      }
    }

    return bestMatch;
  }

  return {
    roster: ENROLLED,
    findStudent,
    validate(name) {
      const student = findStudent(name);
      return {
        isEnrolled: !!student,
        student: student || null
      };
    }
  };
})();

if (typeof window !== "undefined") {
  window.Roster = Roster;
}
